### PR TITLE
Coerce the absence of body into the empty body

### LINKED ISSUE #25: IllegalArgumentException with empty requesty body using OkHttpRequestFactory
When sending a request with empty body, an `IllegalArgumentException` is thrown if one uses the new `OkHttpRequestFactory`. The stacktrace is the following:

```
java.lang.IllegalArgumentException: method POST must have a request body.
    at com.squareup.okhttp.Request$Builder.method(Request.java:244)
    at org.springframework.http.client.OkHttpClientHttpRequest.executeInternal(OkHttpClientHttpRequest.java:85)
    at org.springframework.http.client.AbstractBufferingClientHttpRequest.executeInternal(AbstractBufferingClientHttpRequest.java:48)
    at org.springframework.http.client.AbstractClientHttpRequest.execute(AbstractClientHttpRequest.java:84)
    at org.springframework.http.client.InterceptingClientHttpRequest$RequestExecution.execute(InterceptingClientHttpRequest.java:91)
    at my.super.secret.package.AuthorizationInterceptor.intercept(AuthorizationInterceptor.java:29)
    at org.springframework.http.client.InterceptingClientHttpRequest$RequestExecution.execute(InterceptingClientHttpRequest.java:81)
    at org.springframework.http.client.InterceptingClientHttpRequest.executeInternal(InterceptingClientHttpRequest.java:67)
    at org.springframework.http.client.AbstractBufferingClientHttpRequest.executeInternal(AbstractBufferingClientHttpRequest.java:48)
    at org.springframework.http.client.AbstractClientHttpRequest.execute(AbstractClientHttpRequest.java:84)
    at org.springframework.web.client.RestTemplate.doExecute(RestTemplate.java:536)
    at org.springframework.web.client.RestTemplate.execute(RestTemplate.java:499)
    at org.springframework.web.client.RestTemplate.exchange(RestTemplate.java:447)
```

This is a regression introduced by the new implementation of `OkHttpRequestFactory` added by the M3 release.

### PR DESCRIPTION
**Pull request by WonderCsabo**
Fixes #25.

### CODE REVIEW

**Comment by royclarkson** [comment]
@WonderCsabo thanks for the PR. I'm hoping to have time over the upcoming holidays to work on this and do some testing. If you can add a few tests, that would be a big help. I'll plan on pushing out a 2.0.0.M4 or RC1 with this change, and you can use that to validate against your code.

**Comment by WonderCsabo** [comment]
Thanks for the feedback. Can you point me to some example tests for request factories? I already tested this against my code BTW.

**Comment by royclarkson** [comment]
Here are the related OkHttp tests. Thanks for the help.

https://github.com/spring-projects/spring-android/blob/master/test/spring-android-rest-template-test/src/main/java/org/springframework/http/client/OkHttpClientHttpRequestFactoryTests.java

**Comment by WonderCsabo** [comment]
@royclarkson I added a test. This fails before my fix and passes with may fix. The failure is exactly the same which i experienced in my real app.

**Comment by royclarkson** [comment]
Excellent. Thanks again for the help.

**Comment by WonderCsabo** [comment]
Any chance to check this out @royclarkson?

**Comment by ollide** [comment]
Any update on this? A 2.0.0.M4 release containing the fix would be really nice :+1:

**Comment by WonderCsabo** [comment]
@royclarkson thanks for merging this finally. :relaxed:

**Comment by royclarkson** [comment]
I know. :( too much going on. I'm pushing out a 2.0.0.M4 to get this in a release. We can figure out the OkHttp3 stuff in #29.

**Pull request merged**
